### PR TITLE
Added `START_MEDIA` var to `deployment.md` (pull by a teen)

### PR DESCRIPTION
**Pull request by Navaneeth-Renjith**
## Changes
* Added `START_MEDIA` var
* Added `Monospace` formatting (Removed in some parts)
* Edited some parts of file
### `START_MEDIA`
This var can be used to show media when you start your bot.
> Available to **Bot Mode** users only

Var value should be a telegraph link of a media.

```bash
eg. https://telegra.ph/file/e912739114b56059a8cf3.jpg
```

### CODE REVIEW

**Comment by NavaneethRenjith8282** [comment]
All admins not responding!!!!!!!!

**Comment by jigarvarma2k20** [comment]
Don't replace bold style with mono

**Comment by jigarvarma2k20** [comment]
> Don't replace bold style with mono

@NavaneethRenjith8282

**Comment by NavaneethRenjith8282** [comment]
> Don't replace bold style with mono

`Mono` is for vars.

**Comment by Navaneeth-Renjith** [comment]
> Don't replace bold style with mono

Replaced [`Mono`](https://github.com/theuserge/TheUserge.github.io/pull/18/commits/6e9382b26a3f6c1655dcb61d8d9c9be205cd0ca9) now. @Jigarvarma2005 you can review this.

**Pull request closed without merging**
